version: '3.2'

services:
  demo_cookiecutter_data_experimentation_service:
    container_name: demo_cookiecutter_data_experimentation_container
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./demo_cookiecutter_data_experimentation:/app/demo_cookiecutter_data_experimentation
      - ./data:/app/data
    ports:
      - "8510:8501"
    command:
      - bash
      - -c
      - streamlit run ./demo_cookiecutter_data_experimentation/app.py
